[package]
name = "rationalmath"
version = "0.1.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "aptos-cli-v1.0.3" }

[addresses]
rationalmath = "_"

[dev-addresses]
rationalmath = '0xAB'
